# Generated by Django 4.2.20 on 2025-04-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='익명', max_length=100),
        ),
    ]
