# Generated by Django 4.2.2 on 2025-04-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('agency', models.TextField()),
                ('debut_data', models.DateField()),
                ('is_group', models.BooleanField()),
            ],
        ),
    ]
