# Generated by Django 4.2.20 on 2025-03-29 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    # 1번 설계도에 의존한다는 거임 
    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updates_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
